# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

USER_LIB_PATH = /usr/share/arduino/libraries/
BOARD_TAG     = pro5v328
ARDUINO_PORT  = /dev/ttyUSB0
ARDUINO_LIBS  = Wire

include /home/alek/ArduinoMakefile/Arduino.mk
