# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

USER_LIB_PATH = /usr/share/arduino/libraries/
BOARD_TAG     = uno#pro5v328
ARDUINO_PORT  = /dev/ttyACM0#ttyUSB0
ARDUINO_LIBS  = Wire SPI

include /home/alek/ArduinoMakefile/Arduino.mk
#include /home/artur/Arduino-Makefile/Arduino.mk
